<?php
// +----------------------------------------------------------------------
// | B5LaravelCMF
// +----------------------------------------------------------------------
// | Author: 李恒 <357145480@qq.com>
// +----------------------------------------------------------------------
namespace backend\controllers;

use common\cache\AdpositionCache;
use common\cache\DictCache;
use common\cache\RedtypeCache;
use common\services\AdlistService;
use Yii;

/**
 * 推荐信息控制器
 * Class AdlistController
 * @package backend\controllers
 */
class AdlistController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->service=new AdlistService();
        if(IS_GET && !IS_AJAX){
            Yii::$app->view->params['typelist']=DictCache::get('sys_redtype_type','',true);
            Yii::$app->view->params['funclist']=RedtypeCache::get('',true,true);
            Yii::$app->view->params['adposlist']=AdpositionCache::get('',false);
        }
    }
    public function actionIndex()
    {
        if(IS_GET && !IS_AJAX){
            if(strtolower(ACTION_NAME)=='index'){
                Yii::$app->view->params['adposlist']=AdpositionCache::get('',true);
            }else{
                Yii::$app->view->params['adposlist']=AdpositionCache::get('',false);
            }
        }
        return parent::actionIndex(); // TODO: Change the autogenerated stub
    }
}
