<?php
// +----------------------------------------------------------------------
// | B5LaravelCMF
// +----------------------------------------------------------------------
// | Author: 李恒 <357145480@qq.com>
// +----------------------------------------------------------------------
namespace backend\controllers;

use common\services\AdminService;
use common\services\RoleService;
use Yii;

/**
 * 人员管理控制器
 * Class AdminController
 * @package backend\controllers
 */
class AdminController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->service = new AdminService();
        IS_GET && !IS_AJAX && Yii::$app->view->params['rolelist']=(new RoleService())->getAll([],['id','name'],[],'id,name',[['listsort','asc'],['id','asc']]);
    }
}
