<?php
// +----------------------------------------------------------------------
// | B5YiiCMF
// +----------------------------------------------------------------------
// | Author: 李恒 <357145480@qq.com>
// +----------------------------------------------------------------------
namespace backend\controllers;

use common\services\AdminRoleService;
use Yii;

/**
 * 人员和权限分组控制器
 * Class AdminController
 * @package backend\controllers
 */
class AdminroleController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->service = new AdminRoleService(false);
        IS_GET && !IS_AJAX && Yii::$app->view->params['role_id']=intval(Yii::$app->request->get('role_id'));
    }
    public function actionTree(){
        return $this->service->getList(false);
    }
}
