<?php
// +----------------------------------------------------------------------
// | B5YiiCMF
// +----------------------------------------------------------------------
// | Author: 李恒 <357145480@qq.com>
// +----------------------------------------------------------------------
namespace backend\controllers;

use common\services\ConfigService;
use Yii;

/**
 * 参数配置控制器
 * Class ConfigController
 * @package backend\controllers
 */
class ConfigController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->service=new ConfigService();
        if(IS_GET && !IS_AJAX){
            Yii::$app->view->params['stylelist']=$this->service->styleList();
            Yii::$app->view->params['grouplist']=$this->service->getConfig('sys_config_group');
        }
    }

    public function actionSite(){
        if(IS_POST){
            return $this->service->siteSave();
        }
        $lists=$this->service->getListByGroup();
        return $this->render('',['lists'=>$lists]);
    }
}
