<?php
// +----------------------------------------------------------------------
// | B5YiiCMF
// +----------------------------------------------------------------------
// | Author: 李恒 <357145480@qq.com>
// +----------------------------------------------------------------------
namespace backend\controllers;

use common\services\DictDataService;
use common\services\DictTypeService;
use Yii;

/**
 * 字典数据控制器
 * Class DictdataController
 * @package backend\controllers
 */
class DictdataController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->service=new DictDataService();
        if(IS_GET && !IS_AJAX){
            Yii::$app->view->params['typelist']=(new DictTypeService())->getTypeList();
        }
    }
}
