<?php
// +----------------------------------------------------------------------
// | B5YiiCMF
// +----------------------------------------------------------------------
// | Author: 李恒 <357145480@qq.com>
// +----------------------------------------------------------------------
namespace backend\controllers;

use common\services\MenuService;
use Yii;

/**
 * 菜单控制器
 * Class MenuController
 * @package backend\controllers
 */
class MenuController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->service = new MenuService();
    }

    public function actionIndex()
    {
        if(IS_POST){
            return $this->service->getList(true);
        }
        return parent::actionIndex(); // TODO: Change the autogenerated stub
    }

    public function actionAdd()
    {
        if(IS_GET){
            $parent_name='主目录';
            $parent_id=intval(Yii::$app->request->get('id',0));
            if($parent_id>0){
                $parentInfo=$this->service->info($parent_id);
                if($parentInfo){
                    $parent_name=$parentInfo['name'];
                }else{
                    $parent_id=0;
                }
            }
            Yii::$app->view->params['parent_id']=$parent_id;
            Yii::$app->view->params['parent_name']=$parent_name;
            Yii::$app->view->params['typeList']=$this->service->typeList();
        }
        return parent::actionAdd(); // TODO: Change the autogenerated stub
    }

    public function actionEdit()
    {
        if(IS_GET){
            Yii::$app->view->params['typeList']=$this->service->typeList();
        }
        return parent::actionEdit(); // TODO: Change the autogenerated stub
    }

    public function actionTree(){
        if(IS_POST){
            return $this->service->getTree();
        }else{
            $id = Yii::$app->request->get('id', 0);
            $root = Yii::$app->request->get('root', 1);
            return $this->render('',['menuId'=>$id,'root'=>$root]);
        }
    }
}
