<?php
// +----------------------------------------------------------------------
// | B5LaravelCMF
// +----------------------------------------------------------------------
// | Author: 李恒 <357145480@qq.com>
// +----------------------------------------------------------------------
namespace backend\controllers;

use common\cache\DictCache;
use common\services\NoticeService;
use Yii;

/**
 * 通知公告控制器
 * Class NoticeController
 * @package backend\controllers
 */
class NoticeController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->service = new NoticeService();
        if(IS_GET && !IS_AJAX){
            Yii::$app->view->params['typelist']=DictCache::get('sys_notice_type');
        }
    }

}
