<?php
// +----------------------------------------------------------------------
// | B5YiiCMF
// +----------------------------------------------------------------------
// | Author: 李恒 <357145480@qq.com>
// +----------------------------------------------------------------------
namespace backend\controllers;

use common\services\RoleService;
use Yii;

/**
 * 角色管理控制器
 * Class RoleController
 * @package backend\controllers
 */
class RoleController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->service = new RoleService();
    }

    public function actionAuth(){
        if(IS_POST){
            return $this->service->saveAuth();
        }else{
            $role_id=Yii::$app->request->get('role_id',0);
            if(!$role_id) return $this->toError('参数错误');
            $info=$this->service->info($role_id,false);
            if(empty($info)) return $this->toError('角色信息不存在');
            $menuList=[];

            $lists=$info->menus;
            if($lists){
                foreach ($lists as $menu){
                    $menuList[]=$menu->menu_id;
                }
                unset($lists);
            }
            $menuList=implode(',',$menuList);
            return $this->render("",['info'=>$info,'menuList'=>$menuList]);
        }

    }
}
