<?php
// +----------------------------------------------------------------------
// | B5YiiCMF
// +----------------------------------------------------------------------
// | Author: 李恒 <357145480@qq.com>
// +----------------------------------------------------------------------
namespace backend\controllers;

use common\helpers\commonApi;
use common\models\scratch\ScratchPrize;
use common\models\scratch\ScratchPrizeUsers;
use common\models\scratch\ScratchUsersLogs;
use common\services\scratch\ScratchService;
use Yii;
use function Symfony\Component\String\s;

class ScratchController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->service=new ScratchService();
        $this->view_group='/scratch';
    }

    public function actionInitdata(){
        $scratch_id=intval(Yii::$app->request->get('scratch_id',0));
        if($scratch_id<1) {
            return $this->resError('参数错误');
        }
        $scratch_info=(new ScratchService())->info($scratch_id);
        if(!$scratch_info){
            return $this->resError('活动信息不存在');
        }
        if(IS_GET){
            Yii::$app->view->params['scratchInfo']=$scratch_info;
            return $this->render();
        }else{
            $type=trim(Yii::$app->request->get('type',''));
            if(!in_array($type,['all','prizeusers'])){
                return commonApi::message('参数错误',false);
            }
            switch ($type){
                case 'all':
                    ScratchPrize::deleteAll(['scratch_id'=>$scratch_id]);
                    (new ScratchService())->drop(['ids'=>$scratch_id]);
                case 'prizeusers':
                    ScratchPrizeUsers::deleteAll(['scratch_id'=>$scratch_id]);
                    ScratchUsersLogs::deleteAll(['scratch_id'=>$scratch_id]);
                    break;
            }
            return commonApi::message('操作完成',true);
        }
    }
}