<?php
// +----------------------------------------------------------------------
// | B5YiiCMF
// +----------------------------------------------------------------------
// | Author: 李恒 <357145480@qq.com>
// +----------------------------------------------------------------------
namespace backend\controllers;

use common\services\scratch\ScratchPrizeService;
use common\services\scratch\ScratchService;
use Yii;

class ScratchprizeController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->service=new ScratchPrizeService();
        $this->view_group='/scratch/prize';

    }
    public function actionIndex()
    {
        if(IS_GET){
            $scratch_id=intval(Yii::$app->request->get('scratch_id',0));
            if($scratch_id<1) {
                return $this->resError('参数错误');
            }
            $scratch_info=(new ScratchService())->info($scratch_id);
            if(!$scratch_info){
                return $this->resError('活动信息不存在');
            }
            Yii::$app->view->params['scratchInfo']=$scratch_info;
        }
        return parent::actionIndex(); // TODO: Change the autogenerated stub
    }
}