<?php
// +----------------------------------------------------------------------
// | B5YiiCMF
// +----------------------------------------------------------------------
// | Author: 李恒 <357145480@qq.com>
// +----------------------------------------------------------------------
namespace backend\controllers;

use common\services\scratch\ScratchPrizeService;
use common\services\scratch\ScratchPrizeUsersService;
use common\services\scratch\ScratchService;
use Yii;

class ScratchprizeusersController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->service=new ScratchPrizeUsersService();
        $this->view_group='/scratch/prizeusers';

    }
    public function actionIndex()
    {
        if(IS_GET){
            $scratch_id=intval(Yii::$app->request->get('scratch_id',0));
            if($scratch_id<1) {
                return $this->resError('参数错误');
            }
            $scratch_info=(new ScratchService())->info($scratch_id);
            if(!$scratch_info){
                return $this->resError('活动信息不存在');
            }
            $prizeList=(new ScratchPrizeService())->getAll([['scratch_id'=>$scratch_id]],['id','title'],[],'id,title');
            Yii::$app->view->params['prizeList']=$prizeList;
            Yii::$app->view->params['scratchInfo']=$scratch_info;
        }
        return parent::actionIndex(); // TODO: Change the autogenerated stub
    }


    public function actionSetstatus()
    {
        return $this->service->setStatus([],['get_time'=>date('Y-m-d H:i:s',time())]);
    }
}