<?php
// +----------------------------------------------------------------------
// | B5YiiCMF
// +----------------------------------------------------------------------
// | Author: 李恒 <357145480@qq.com>
// +----------------------------------------------------------------------
namespace backend\controllers;

use common\services\StructService;
use Yii;

/**
 * 组织构架控制器
 * Class StructController
 * @package backend\controllers
 */
class StructController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->service=new StructService();
    }

    public function actionIndex()
    {
        if (IS_POST) {
            return $this->service->getList(true);
        }
        return parent::actionIndex(); // TODO: Change the autogenerated stub
    }

    public function actionAdd()
    {
        if (IS_GET) {
            $parent_name = '-';
            $parent_id = Yii::$app->request->get('id');
            if (empty($parent_id)) {
                $parent_id = $this->service->getFirstId();
            }
            $parentInfo = $this->service->info($parent_id);
            if ($parentInfo) {
                $parent_name = $parentInfo['name'];
            }
            Yii::$app->view->params['parent_id']=$parent_id;
            Yii::$app->view->params['parent_name']=$parent_name;
        }
        return parent::actionAdd(); // TODO: Change the autogenerated stub
    }

    public function actionTree()
    {
        if (IS_POST) {
            return $this->service->getTree();
        } else {
            $id =Yii::$app->request->get('id');
            $ismult = Yii::$app->request->get('ismult');
            if (empty($id) && empty($ismult)) {
                $id = $this->service->getFirstId();
            }
            return $this->render('',['ismult'=>$ismult,'structId'=>$id]);
        }
    }
}
