<?php
// +----------------------------------------------------------------------
// | B5YiiCMF
// +----------------------------------------------------------------------
// | Author: 李恒 <357145480@qq.com>
// +----------------------------------------------------------------------
namespace backend\controllers;

use common\services\web\WebAdService;
use common\services\web\WebPosService;
use Yii;

class WebadController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->service=new WebAdService();
        $this->view_group='/web/webad';
        if(IS_GET && !IS_AJAX){
            Yii::$app->view->params['posList']=(new WebPosService())->getAll([],[],[],'id');
        }
    }
}