<?php
// +----------------------------------------------------------------------
// | B5LaravelCMF
// +----------------------------------------------------------------------
// | Author: 李恒 <357145480@qq.com>
// +----------------------------------------------------------------------
namespace backend\controllers;

use common\services\web\WebCatService;
use Yii;

class WebcatController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->service=new WebCatService();
        $this->view_group='/web/webcat';
        if(IS_GET && !IS_AJAX){
            Yii::$app->view->params['typeList']=$this->service->typeList();
        }
    }
    public function actionAdd()
    {
        if(IS_GET){
            $parent_name='顶级菜单';
            $parent_id=intval(Yii::$app->request->get('id',0));
            if($parent_id>0){
                $parentInfo=$this->service->info($parent_id);
                if($parentInfo){
                    $parent_name=$parentInfo['name'];
                }else{
                    $parent_id=0;
                }
            }
            Yii::$app->view->params['parent_id']=$parent_id;
            Yii::$app->view->params['parent_name']=$parent_name;
        }
        return parent::actionAdd(); // TODO: Change the autogenerated stub
    }
    public function actionTree(){
        if(IS_POST){
            return $this->service->getTree();
        }else{
            $id = intval(Yii::$app->request->get('id', 0));
            $root = Yii::$app->request->get('root', 1);
            return $this->render('',['menuId'=>$id,'root'=>$root]);
        }
    }
}