<?php
// +----------------------------------------------------------------------
// | B5YiiCMF
// +----------------------------------------------------------------------
// | Author: 李恒 <357145480@qq.com>
// +----------------------------------------------------------------------
namespace common\models;

use common\services\AdminRoleService;
use common\services\AdminStructService;
use Yii;

/**
 * This is the model class for table "b5net_admin".
 *
 * @property int $id
 * @property string $username 登录名
 * @property string $password 登录密码
 * @property string $realname 人员姓名
 * @property string $status 状态
 * @property string|null $note 备注
 * @property string|null $create_time 创建时间
 * @property string|null $update_time 更新时间
 * @property string|null $last_time 登录时间
 * @property string|null $last_ip 登录ip
 */
class Admin extends BaseModel
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'b5net_admin';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['username', 'realname', 'password', 'status'], 'trim'],
            [['username'], 'required'],
            [['username', 'realname'], 'string', 'max' => 30, 'min' => 2],
            ['username', 'match', 'pattern' => '/^[A-Za-z0-9_-]+$/', 'message' => '{attribute}必须是字母、数字、下划线或破折号'],
            [['password'], 'string', 'max' => 20, 'min' => 6],
            [['note'], 'string', 'max' => 255],
            ['status', 'in', 'range' => [0, 1]],
            [['username'], 'unique'],
            [['create_time', 'update_time', 'last_time', 'last_ip'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => '登录名',
            'password' => '登录密码',
            'realname' => '人员姓名',
            'status' => '状态',
            'note' => '备注',
            'create_time' => '创建时间',
            'update_time' => '更新时间',
            'last_time' => '登录时间',
            'last_ip' => '登录ip',
        ];
    }

    public function getStructs(){
        return $this->hasMany(Struct::class, ['id' => 'struct_id'])->viaTable(AdminStruct::tableName(), ['admin_id' => 'id'])->asArray();
    }

    public function getRoles(){
        return $this->hasMany(Role::class, ['id' => 'role_id'])->viaTable(AdminRole::tableName(), ['admin_id' => 'id'])->asArray();
    }

    public function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub
        AdminStructService::update($this->id,'');
        AdminRoleService::update($this->id,'');
    }
}
