<?php
// +----------------------------------------------------------------------
// | B5LaravelCMF
// +----------------------------------------------------------------------
// | Author: 李恒 <357145480@qq.com>
// +----------------------------------------------------------------------
namespace common\models;

use yii\db\ActiveRecord;
use yii\db\Expression;
use Yii;

/**
 * 人员管理-模型
 * Class BaseModel
 * @package App\Models
 */
class BaseModel extends ActiveRecord
{
    //是否自动维护时间戳
    public $timestamps = true;

    public $primaryKey='id';

    public function getQuery(){
        return self::find();
    }
    /**
     * 获取所有数据
     * @param array $map
     * @param array $select
     * @param array $pageData
     * @param string $listKey
     * @param array $sort
     * @param bool $debug
     * @return array
     */
    public function getList(array $map = [], array $select = [], array $pageData = [], string $listKey = '', array $sort = [['id', 'asc']],$debug=false)
    {
        $list = [];
        $query = self::find();
        $query=$query->where('1');

        if (!empty($map)) {
            $query = $this->whereFormat($query, $map);
        }

        if (!empty($select)) {
            $query = $query->select($select);
        }
        if (!empty($pageData)) {
            $query = $query->offset($pageData[0])->limit($pageData[1]);
        }
        if (!empty($sort)) {
            $orderBy=[];
            foreach ($sort as $sortkey=>$sortval){
                if(is_array($sortval)){
                    $orderBy[]=$sortval[0].' '.$sortval[1];
                }else{
                    $orderBy[]=$sortkey.' '.$sortval;
                }
            }
            $orderBy=implode(',',$orderBy);
            $query = $query->orderBy($orderBy);
        }
        if ($listKey) {
            if(strpos($listKey,',')){
                $listKey=explode(',',$listKey,2);
            }
        }
        foreach ($query->each(30) as $info) {
            $info=$info->toArray();
            if ($listKey) {
                if(is_array($listKey)){
                    if($listKey[0]==$listKey[1]){
                        $list[] = $info[$listKey[0]];
                    }else{
                        $list[$info[$listKey[0]]] = $info[$listKey[1]];
                    }
                }else{
                    $list[$info[$listKey]] = $info;
                }
            } else {
                $list[] = $info;
            }
        }
        return $list;
    }

    /**
     * 获取数量
     * @param array $map
     * @return int|string
     */
    public function getCount(array $map = [])
    {
        $query = self::find();
        $query=$query->where('1');
        if (!empty($map)) {
            $query = $this->whereFormat($query, $map);
        }
        return $query->count();
    }

    /**
     * 获取单条信息
     * @param $map
     * @param bool $isArr
     * @return bool|BaseModel|mixed|null
     */
    public function info($map,$isArr=false)
    {
        if (!$map) return false;
        if (is_array($map)) {
            $info = $this->whereFormat(self::find(), $map);
            $info = $info->one();
        } else {
            $info = self::findOne($map);
        }
        if($isArr && $info){
            return $info->toArray();
        }
        return $info;
    }

    /**
     * 自定义保存
     * @param $data
     * @param string $key
     * @return bool
     */
    public function edit($data,$key='id'){
        if(!$data || !isset($data[$key])) return false;
        $info=self::findOne($data[$key]);
        if($info){
            unset($data[$key]);
            if($info->load($data,'') && $info->save(false)){
                return true;
            }
        }
        return false;
    }

    /**
     * 更新数据
     * @param array $data
     * @return bool
     */
    public function save($runValidation = true, $attributeNames = null)
    {
        if($this->timestamps){
            if($this->isNewRecord){
                $this->create_time=date('Y-m-d H:i:s',time());
            }
            $this->update_time=date('Y-m-d H:i:s',time());
        }
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }

    /**
     * 批量插入
     * @param $field
     * @param $data
     * @return bool|int
     * @throws \yii\db\Exception
     */
    public function insertAll($field,$data){
        if(!$data || !$field) return false;
        return Yii::$app->db->createCommand()->batchInsert($this::tableName(),$field,$data)->execute();
    }
    /**
     * 删除
     * @param mixed $id
     * @param string $field
     * @return bool
     */
    public function drop($id, string $field = '')
    {
        if (empty($id)) return false;
        if (is_array($id)) {
            $idArr = $id;
        } else {
            $id = trim($id, ',');
            $idArr = explode(',', $id);
        }
        $idArr = array_unique($idArr);
        if (empty($idArr)) return false;
        $field = $field ?: $this->primaryKey;
        if (count($idArr) ==1) {
            $idArr = $idArr[0];
        }
        return self::deleteAll([$field => $idArr]);
    }

    /**
     * 清空表
     */
    public function trash(){
        Yii::$app->db->createCommand()->truncateTable($this::tableName())->execute();
        return true;
    }

    /**
     * 处理数组where条件
     * @param $query
     * @param $map
     * @return mixed
     */
    public function whereFormat($query, $map)
    {
        if (empty($map)) return $query;
        if(is_array($map)){
            foreach($map as $wval){
                if (count($wval) == 3){
                    if($wval[1]==='findinset') {
                        $wval=new Expression('FIND_IN_SET("'.$wval[2].'", '.$wval[0].')');
                    }elseif ($wval[1]==='in'){
                        $wval=[$wval[0]=>$wval[2]];
                    }elseif ($wval[1]==='='){
                        $wval=[$wval[0]=>$wval[2]];
                    }
                }
                $query=$query->andWhere($wval);
            }
        }else{
            $query=$query->andWhere($map);
        }
        return $query;
    }
}
