<?php
// +----------------------------------------------------------------------
// | B5LaravelCMF
// +----------------------------------------------------------------------
// | Author: 李恒 <357145480@qq.com>
// +----------------------------------------------------------------------
namespace common\services;

use common\models\Role;
use common\helpers\commonApi;

/**
 * 权限分组管理
 * Class RoleService
 * @package App\Services
 */
class RoleService extends BaseService
{
    public function __construct(bool $loadValidate = true)
    {
        $this->model = new Role();
        $this->validate = $loadValidate;
    }

    /**
     * 保存授权信息
     * @return array
     */
    public function saveAuth(){
        $input=\Yii::$app->request->post();
        $id=$input['id']??0;
        $treeId=$input['treeId']??'';
        if(empty($id)) return commonApi::message('参数错误',false);

        //演示限制
        if(commonApi::system_isDemo()){
            return $this->demo_system();
        }

        (new RoleMenuService())->update($id,$treeId);
        return commonApi::message('授权成功',true);
    }

    /**
     * 获取授权菜单
     * @param $roleId
     * @param bool $isArr
     * @return array|string
     */
    public function authList($roleId,bool $isArr=true){
        $list=[];
        if($roleId){
            $list=(new RoleMenuService())->getRoleMenuList($roleId);
        }
        $list=$isArr?($list?:[]):($list?implode(',',$list):'');
        return $list;
    }

    public function after_drop($data)
    {
        (new RoleMenuService())->drop($data,'role_id');
        return parent::after_drop($data); // TODO: Change the autogenerated stub
    }
}
