<?php
// +----------------------------------------------------------------------
// | B5YiiCMF
// +----------------------------------------------------------------------
// | Author: 李恒 <357145480@qq.com>
// +----------------------------------------------------------------------
namespace common\services\scratch;

use common\cache\ScratchCache;
use common\helpers\commonApi;
use common\models\scratch\Scratch;
use common\services\BaseService;

/**
 * 推荐信息
 * Class AdlistService
 * @package App\Services
 */
class ScratchService extends BaseService
{
    public function __construct(bool $loadValidate = true)
    {
        $this->model = new Scratch();
        $this->validate = $loadValidate;
    }

    public function after_add($data)
    {
        $this->delcache($data['id']);
        return parent::after_add($data); // TODO: Change the autogenerated stub
    }

    public function after_edit($data)
    {
        $this->delcache($data['id']);
        return parent::after_edit($data); // TODO: Change the autogenerated stub
    }

    public function after_drop($data, $field)
    {
        $this->delcache($data['ids']);

        return parent::after_drop($data, $field); // TODO: Change the autogenerated stub
    }
    /**
     * 清除缓存
     * @return array
     */
    public function delcache($id)
    {
        ScratchCache::clear($id);
        return commonApi::message('清理缓存完成', true);
    }
}
