<?php
// +----------------------------------------------------------------------
// | B5YiiCMF
// +----------------------------------------------------------------------
// | Author: 李恒 <357145480@qq.com>
// +----------------------------------------------------------------------
namespace common\services\scratch;

use common\models\scratch\ScratchPrize;
use common\services\BaseService;

/**
 * 推荐信息
 * Class AdlistService
 * @package App\Services
 */
class ScratchPrizeService extends BaseService
{
    public function __construct(bool $loadValidate = true)
    {
        $this->model = new ScratchPrize();
        $this->validate = $loadValidate;
    }
    public function before_op($data, $type = '')
    {
        if($type=='add' || $type=='edit'){
            $data['thumbimg']=(isset($data['thumbimg']) && $data['thumbimg'])?(is_array($data['thumbimg'])?$data['thumbimg'][0]:$data['thumbimg']):'';
        }
        return parent::before_op($data, $type); // TODO: Change the autogenerated stub
    }

}
