<?php
// +----------------------------------------------------------------------
// | B5LaravelCMF
// +----------------------------------------------------------------------
// | Author: 李恒 <357145480@qq.com>
// +----------------------------------------------------------------------
namespace common\services\web;

use common\helpers\commonApi;
use common\models\web\WebCat;
use common\services\BaseService;

/**
 * 网站栏目
 * Class WebCatService
 * @package App\Services
 */
class WebCatService extends BaseService
{
    public function __construct(bool $loadValidate = true,bool $loadModel=true)
    {
        $loadModel && $this->model = new WebCat();
        $this->validate = $loadValidate;
    }
    public function after_getList($list,$param)
    {
        if($list){
            foreach ($list as $key=>$value){
                $list[$key]['type_name']=$this->typeList($value['type']);
            }
        }
        return parent::after_getList($list,$param); // TODO: Change the autogenerated stub
    }
    /**
     * 内容类型
     * @param null $type
     * @return array|mixed|string
     */
    public function typeList($type=null){
        $arr=[
            'list' => '图文信息',
            'goods' => '产品信息',
            'page' => '单页介绍',
            'link' => '外链跳转',
            'none' => '无类型'
        ];
        if(is_null($type)) return $arr;
        return $arr[$type]??'';
    }

    /**
     * 获取菜单信息时返回父菜单名称
     * @param $id
     * @param bool $isArray
     * @return mixed
     */
    public function info($id, $isArray = true)
    {
        $info = parent::info($id, $isArray);
        if ($info) {
            $info['parent_name'] = '顶级菜单';
            if ($info['parent_id'] > 0) {
                $parentInfo = $this->model->info($info['parent_id'], true);
                if ($parentInfo) {
                    $info['parent_name'] = $parentInfo['name'];
                } else {
                    $info['parent_name'] = '';
                }
            }
            if($info['type']) $info['type_name']=$this->typeList($info['type']);
        }
        return $info;
    }

    /**
     * 选择父级菜单的菜单树数据
     * @return array
     */
    public function getTree()
    {

        $list = $this->getAll([], ['id', 'parent_id', 'name','type'], [], '', [['parent_id', 'asc'], ['listsort', 'asc'],['id','asc']]);
        $root = \Yii::$app->request->get('root', 1);
        if ($root) {
            $first = [
                'id' => 0,
                'parent_id' => -1,
                'name' => '顶级菜单',
                'type' => 'none'
            ];
            array_unshift($list, $first);
        }
        return commonApi::message('操作成功', true, $list);
    }

}
