<?php
// +----------------------------------------------------------------------
// | B5YiiCMF
// +----------------------------------------------------------------------
// | Author: 李恒 <357145480@qq.com>
// +----------------------------------------------------------------------
namespace h5\controllers;

use common\cache\ScratchCache;
use common\helpers\commonApi;
use common\models\scratch\ScratchPrize;
use common\models\scratch\ScratchPrizeUsers;
use common\models\scratch\ScratchUsersLogs;
use Yii;

class ScratchController extends WechatController
{
    public $enableCsrfValidation=false;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->actService=new ScratchCache();
    }
    public function actionIndex()
    {
        $getprizelist=ScratchPrizeUsers::find()->where(['scratch_id'=>$this->actInfo['id']])->select(['nickname','prize_name'])->orderBy('id desc')->limit(20)->cache(30)->asArray()->all();
        $leftnum=-1;
        if($this->actInfo['daynum']>0){
            $hasnum=ScratchUsersLogs::find()->where(['openid'=>$this->wechatInfo['openid'],'create_time'=>date('Y-m-d',time()),'scratch_id'=>$this->actInfo['id']])->select(['id'])->count();
            $leftnum=$hasnum>$this->actInfo['daynum']?0:($this->actInfo['daynum']-$hasnum);
        }
        $prizeList=ScratchPrize::find()->where(['scratch_id'=>$this->actInfo['id'],'status'=>1])->select(['id','title','name'])->cache(100)->asArray()->all();
        return $this->renderPartial('',['scratchInfo'=>$this->actInfo,'getprizelist'=>$getprizelist,'leftnum'=>$leftnum,'prizeList'=>$prizeList]);
    }

    /**
     * 抽奖
     * @return array
     */
    public function actionGetprize(){
        $startTime=strtotime($this->actInfo['start_time']);
        $endTime=strtotime($this->actInfo['end_time']);
        $nowTime=time();
        $nowDay=date('Y-m-d',$nowTime);
        if($startTime>$nowTime){
            return commonApi::message('活动未开始',false);
        }
        if($endTime<$nowTime) {
            return commonApi::message('活动已经结束',false);
        }

        //刮奖次数判断
        $hascount=ScratchUsersLogs::find()->where(['openid'=>$this->wechatInfo['openid'],'daytime'=>$nowDay,'scratch_id'=>$this->actInfo['id']])->count();//查询刮奖次数统计信息

        if($this->actInfo['daynum']>0 && $hascount>=$this->actInfo['daynum']){ //开启每日刮奖上限
            return commonApi::message('您今天的刮奖次数已用完',false);
        }
        $getprize=['id'=>0,'name'=>'很遗憾','title'=>'未中奖','img'=>''];

        //每天最多中一次奖
        $hasget=ScratchPrizeUsers::find()->where(['openid'=>$this->wechatInfo['openid'],'scratch_id'=>$this->actInfo['id'],'daytime'=>$nowDay])->select(['id'])->one();
        $canget=$hasget?false:true;

        if($canget) {
            $prizeList=ScratchPrize::find()->where(['scratch_id'=>$this->actInfo['id'],'status'=>1])->asArray()->all();
            $count = count($prizeList);
            if ($count) {
                $index = mt_rand(0, $count - 1);
                $prizeinfo = $prizeList[$index];
                if ($prizeinfo && $prizeinfo['isuse'] && $prizeinfo['chance']>0 && $prizeinfo['allnumber']>0) {
                    if (mt_rand(1, $prizeinfo['chance']) == $prizeinfo['chance']) {
                        $hasnum=ScratchPrizeUsers::find()->where(['prize_id'=>$prizeinfo['id'],'scratch_id'=>$this->actInfo['id']])->count();
                        if($hasnum<$prizeinfo['allnumber']){
                            $getprize = ['id' => $prizeinfo['id'], 'name' => $prizeinfo['name'], 'title' => $prizeinfo['title'],'img'=>$prizeinfo['thumbimg']];
                        }
                    }
                }
            }
        }
        if ($getprize['id']) {
            $model=new ScratchPrizeUsers();
            $model->scratch_id=$this->actInfo['id'];
            $model->prize_id=$getprize['id'];
            $model->prize_name=$getprize['title'].'：'.$getprize['name'];
            $model->prize_img=$getprize['img'];
            $model->openid=$this->wechatInfo['openid'];
            $model->nickname=$this->wechatInfo['nickname'];
            $model->headimg=$this->wechatInfo['headimg'];
            $model->daytime=$nowDay;
            $model->create_time=date('Y-m-d H:i:s',$nowTime);
            $model->status=0;
            $model->getcode=$getprize['id'].time().mt_rand(1000,9999);
            //添加中奖记录
            $rs=$model->save(false);
            if(!$rs){
                $getprize=['id'=>0,'name'=>'很遗憾','title'=>'未中奖','img'=>''];
            }
        }

        //添加抽奖记录
        $logModel=new ScratchUsersLogs();
        $logModel->openid=$this->wechatInfo['openid'];
        $logModel->scratch_id=$this->actInfo['id'];
        $logModel->daytime=$nowDay;
        $logModel->create_time=date('Y-m-d H:i:s',$nowTime);
        $logModel->save(false);

       return commonApi::message('操作成功',true,['info'=>$getprize]);
    }

    /**
     * 我的奖品
     * @return array
     */
    public function actionMyprize(){
        $list=ScratchPrizeUsers::find()->where(['openid'=>$this->wechatInfo['openid'],'scratch_id'=>$this->actInfo['id']])->select(['id','prize_name','status','prize_img','create_time','getcode'])->asArray()->all();
        return commonApi::message('操作成功',true,['list'=>$list]);
    }
}